### ISSUE TITLE
Return proper exit codes from commands

### ISSUE THREAD

**Issue by IMcD23** [holzschu/ios_system#15] opened 2018-01-30 23:14 UTC
It seems that most everything currently returns 0, even when things fail. The following should be happening:

When a command calls exit(status_code), or its main method returns, store exit code, then call pthread_exit, and return exit code.

**Comment by IMcD23** [comment] 2018-01-30 23:22
Looks like `run_function` discards the return code of the function that it runs. Should be easy enough to store that in the parameters passed in, and read it after `pthread_join`?

**Comment by holzschu** [comment] 2018-01-31 10:35
I'll try to work on it. Most of the time, the program does not exit through `run_function`, because it exits through `pthread_exit`. That's the main reason for discarding the return code of `p->function`: it is almost never written (and especially not written when something happened). 

Now that there is a cleanup function, I may have a bit more leeway to get a return value. It would have to be stored in a global variable (according to the man page of `pthread_exit`), which causes issue if several threads try to access it at the same time. But maybe a thread-local variable could work if treated in the cleanup function. It will need some experiments.

What is the expected behaviour for piped commands? Is the return value the value for the last command?

**Comment by holzschu** [comment] 2018-02-24 21:14
I think I have solved this issue. The bad news is I used a global variable (`global_errno`) and redefined exit as a function.

You can test it with commit b5f1cb5

**Comment by holzschu** [comment] 2018-03-06 07:32
Can I close this issue?

**Closed** 2018-05-01 16:45 UTC
Labels: fix committed
